### ISSUE TITLE
change 'gauge creation fee' to be `minimal initial deposit` instead

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/osmosis#22]
The incentives module implements `gauge creation fee` for gauges that created manually.
We plan to create manual gauges for lockdrops

currently
```
var (
	// CreateGaugeFee is the fee required to create a new gauge.
	CreateGaugeFee = sdk.NewInt(50 * 1_000_000)
	// AddToGagugeFee is the fee required to add to gauge.
	AddToGaugeFee = sdk.NewInt(25 * 1_000_000)
)
```

@shaolin-flow leave it or remove?

**Comment by shaolin-flow** [comment]
@mtsitrin let's remove unless it opens a DoS attack vector.

**Comment by mtsitrin** [comment]
we can set min initial deposit instead
e.g create gauge with at least 1000DYM

instead of charging fee for the community pool

**Comment by shaolin-flow** [comment]
@mtsitrin that sounds good

**Comment by mtsitrin** [comment]
decided to leave AS-IS
requiring minimal amount is limiting the usage of different tokens for incentives

**Comment by yishay-dym** [comment]
Approved
